; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;[env:cubecell_gps]
;board = cubecell_gps
; change microcontroller
;board_build.mcu = asr650x
; change MCU frequency
;board_build.f_cpu = 48000000L
;lib_deps = eiannone/Heltec_Esp32_Display@^0.1.0

[env:cubecell_board] ; HTCC-AB01 V1 seems to work well with V2 boards as well
board = cubecell_board_v2   ; SHOULD BE 'cubecell_board' But the battery voltage measurement is wrong with this setting
board_build.mcu = asr6501 ; Different MCU for V1 (BATTERY VOLTAGE MEASURMENT PROBLEMS)
board_build.f_cpu = 48000000L

;[env:cubecell_board_v2]   ; HTCC-AB01 V2
;board = cubecell_board_v2   ; cubecell_board_v2
;board_build.mcu = asr6502x      ; asr6502x Different MCU for V2 (BATTERY VOLTAGE WILL SHOW 0 IF WRONG MCU) 
;board_build.f_cpu = 48000000L

;[env:cubecell_board_plus] ;https://heltec.org/project/htcc-ab02/
;platform = heltec-cubecell
;board = cubecell_board_plus
; change microcontroller
;board_build.mcu = asr6502
; change MCU frequency
;board_build.f_cpu = 48000000L

;[env:latest_stable]   ;none solar cubecell
;board = cubecell_capsule

;[env:cubecell_capsule_solar_sensor]   ; solar cubecell
;board = cubecell_capsule_solar_sensor

platform = heltec-cubecell
framework = arduino

monitor_speed = 115200
monitor_filters = default, time
board_build.arduino.lorawan.region = EU868
board_build.arduino.lorawan.adr = ON
board_build.arduino.lorawan.debug_level = FREQ_AND_DIO